How to use MPI to debug MPI program
ImperialCollegeLondon/icl-rcs-user-guide pull request #1
Opened 2024-03-18 14:57 UTC by lkr-ind

In this PR, I have added some documentation about the debuggers and how we can use GDB to debug an MPI program. In the absence of a commercial debugger, this would prove useful to the users who are developing their own code.

2024-03-18 16:05 UTC, davidhemp commented on docs/hpc/advanced/debugging_mpi_programs/gdb_mpi_debug.md
> +Consider that you have an MPI program as shown below. The sample program given below is simple MPI program that performs addition and multiplication on each rank and prints the result. The first argu
```suggestion
Consider that you have an MPI program as shown below. The sample program given below is simple MPI program that performs addition and multiplication on each rank and prints the result. The first argument to the multiplication functions is the rank of the process and the second argument is the size of the communicator (this is actually the bug  which is there in the code below and our task is to use gdb on such programs to find the issue). We will create a simple  program using functions so that you can step inside while debugging. Let us assume that the file is named `mpi_debug.cpp`.
```

2024-03-18 16:17 UTC, davidhemp commented on docs/hpc/advanced/debugging_mpi_programs/gdb_mpi_debug.md
> +    int rank, size;
```suggestion
    int rank, size, hostnamelen;
```

2024-03-18 16:18 UTC, davidhemp commented on docs/hpc/advanced/debugging_mpi_programs/gdb_mpi_debug.md
> +
```suggestion
    MPI_Get_processor_name (hostname, &hostnamelen);
```

2024-03-18 16:27 UTC, davidhemp commented on docs/hpc/advanced/debugging_mpi_programs/gdb_mpi_debug.md
> +where `2>&1` is used to redirect the standard error to the standard output and `&` is used to run the process in the background.
```suggestion
where `2>&1` is used to redirect the standard error to the standard output and `&` is used to run the process in the background. When this is run a PID number will be returned which will be needed to attach gdb.
```

2024-03-19 10:21 UTC, davidhemp commented on docs/hpc/advanced/debugging_mpi_programs/gdb_mpi_debug.md
> +And, finally we can see that the issue is with the value of `b` which is `1` and not `6`. This is the bug in the code and we can fix it now.
```suggestion
And, finally we can see that the issue is with the value of `b` which is `1` and not `2`. This is the bug in the code and we can fix it now by going back and setting num2 = size. Again this is a toy example but helps demonstrate the how to find a bug in a code base using a debugger.
```

2024-03-19 10:37 UTC, davidhemp requested changes
cpp file needs correcting

2024-03-19 11:04 UTC, lkr-ind commented on docs/hpc/advanced/debugging_mpi_programs/gdb_mpi_debug.md
> +    int rank, size;
I will add the code as suggested.

2024-03-19 11:04 UTC, lkr-ind commented on docs/hpc/advanced/debugging_mpi_programs/gdb_mpi_debug.md
> +
I will use the correct code and push it again so that we can merge it.

2024-03-19 11:16 UTC, merged