Updated hx1 docs to make it clearer regarding usage.
ImperialCollegeLondon/icl-rcs-user-guide pull request #7
Opened 2024-05-14 14:58 UTC by dithwick

2024-05-14 15:02 UTC, murraycollier commented on docs/hpc/pilot/hx1.md
Maybe one more line that says something like.

"If you are in any doubt whether your job is suited to single node or multi node please contact RCS"

2024-05-14 15:02 UTC, murraycollier approved these changes

2024-05-15 12:05 UTC, dithwick commented on docs/hpc/pilot/hx1.md
@murraycollier - good idea, updated!

2024-05-15 14:54 UTC, slacalle requested changes
got a a typo on line 6 of pilot/hx1.md

2024-05-15 14:54 UTC, slacalle commented on docs/hpc/pilot/hx1.md
> +* GPGPU accelerated applications such as those utilising CUDA.
typo "GPU"

2024-05-15 15:17 UTC, slacalle approved these changes

2024-05-15 15:18 UTC, merged